[tool.poetry]
name = "jabberwocky-container-manager"
version = "0.1.0"
description = "Container manager for the Jabberwocky project"
authors = ["Kippiii <ianorzel@gmail.com>"]
license = "MIT"
readme = "README.md"
packages = [{include = "jabberwocky_container_manager"}]

[tool.poetry.dependencies]
python = "^3.10"
black = "^22.8.0"
mypy = "^0.982"
pylint = "^2.15.3"
pytest = "^7.1.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
